const dbTables = {
  users: 'users',
  designations: 'designations',
  roles: 'roles',
  userRoles: 'user_roles',
  countries: 'countries',
  leaveTypes: 'leave_types',
  leaveCredits: 'leave_credits',
  fiscalYears: 'fiscal_years',
  leaveRequests: 'leave_requests',
  notifications: 'notifications',
  cafes: 'cafes',
  menuCategories: 'menu_categories',
  menuUnis: 'menu_units',
  menuItems: 'menu_items',
  orders: 'orders',
  orderItems: 'order_items',
  orderStatus: 'order_status',
  payments: 'payments',
  payment_status: 'payment_status',
  reviews: 'reviews',
  colleges: 'colleges',
  groups: 'groups',
  userGroups: 'user_groups',
  departments: 'departments',
  courses: 'courses',
  events: 'events',
  eventManagers: 'event_managers',
  eventOrders: 'event_orders',
  cafeManagers: 'cafe_managers',
  interCafeOrders: 'inter_cafe_orders',
  eventOrganizations: 'event_organizations',
} as const;

export default dbTables;
