export default {
  id: ':id',
  slash: '/',
  home: 'home',
  detail: 'detail',
  signup: 'signup',
  menus: 'menus',
  list: 'list',
  signin: 'signin',
  products: 'products',
  leave: 'leave',
  apply: 'apply',
  profile: 'profile',
  employee: 'employee',
  balance: 'balance',
  designation: 'designation',
  role: 'role',
  user: 'user',
  countries: 'countries',
  leaveTypes: 'leave-types',
  leaveRequests: 'leave-request',
  menuDetail: 'menu/details',
  adminOrders: 'admin/orders',
  dashboard: 'dashboard',
  orders: 'orders',
  feedbacks: 'feedbacks',
  userOrders: 'user/orders',
} as const;
