export default {
  leaves: 'leaves',
  balance: 'balance',
  designations: 'designations',
  roles: 'roles',
  user: 'user',
  users: 'users',
  countries: 'countries',
  leaveTypes: 'leave-types',
  leaveCredits: 'leave-credits',
  fiscalYears: 'fiscal-years',
  currentUser: 'currentuser',
  leaveRequests: 'leaveRequests',
  menus: 'menus',
  menuCategories: 'menu-categories',
  orders: 'orders',
} as const;
