import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('analytics').del();

  // Insert seed entries
  await knex('analytics').insert([
    {
      cafe_id: 1,
      date: '2024-08-01',
      order_count: 150,
      total_sales: 1500.0,
      created_by: 1,
      updated_by: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 2,
      date: '2024-08-01',
      order_count: 100,
      total_sales: 1200.0,
      created_by: 1,
      updated_by: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 1,
      date: '2024-08-02',
      order_count: 175,
      total_sales: 1750.0,
      created_by: 2,
      updated_by: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 2,
      date: '2024-08-02',
      order_count: 110,
      total_sales: 1300.0,
      created_by: 2,
      updated_by: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 3,
      date: '2024-08-01',
      order_count: 200,
      total_sales: 2200.0,
      created_by: 3,
      updated_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 3,
      date: '2024-08-02',
      order_count: 180,
      total_sales: 2000.0,
      created_by: 3,
      updated_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 4,
      date: '2024-08-01',
      order_count: 90,
      total_sales: 900.0,
      created_by: 4,
      updated_by: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 4,
      date: '2024-08-02',
      order_count: 85,
      total_sales: 850.0,
      created_by: 4,
      updated_by: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 5,
      date: '2024-08-01',
      order_count: 220,
      total_sales: 2500.0,
      created_by: 5,
      updated_by: 5,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      cafe_id: 5,
      date: '2024-08-02',
      order_count: 210,
      total_sales: 2400.0,
      created_by: 5,
      updated_by: 5,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);
}
