import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('notifications').del();

  // Insert seed entries
  await knex('notifications').insert([
    {
      user_id: 1,
      order_id: 1,
      message: 'Your order has been prepared and is ready for pickup.',
      type: 'OrderStatus',
      status: 'Unread',
      created_by: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 2,
      order_id: 2,
      message: 'Payment successful for your recent order.',
      type: 'Payment',
      status: 'Read',
      created_by: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 3,
      order_id: null,
      message: 'New promotions are available in your favorite cafe!',
      type: 'General',
      status: 'Unread',
      created_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 4,
      order_id: 3,
      message: 'Your order has been shipped and is on its way.',
      type: 'OrderStatus',
      status: 'Unread',
      created_by: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 5,
      order_id: null,
      message: 'There is an issue with your payment method.',
      type: 'Payment',
      status: 'Unread',
      created_by: 5,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 1,
      order_id: 4,
      message: 'Order #4 has been completed successfully.',
      type: 'OrderStatus',
      status: 'Read',
      created_by: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 2,
      order_id: 5,
      message: 'Payment has been processed for order #5.',
      type: 'Payment',
      status: 'Read',
      created_by: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 3,
      order_id: null,
      message: 'Don’t miss our new arrivals in the menu!',
      type: 'General',
      status: 'Unread',
      created_by: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 4,
      order_id: 6,
      message: 'Order #6 has been canceled.',
      type: 'OrderStatus',
      status: 'Read',
      created_by: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      user_id: 5,
      order_id: null,
      message: 'Reminder: Your payment method needs updating.',
      type: 'Payment',
      status: 'Unread',
      created_by: 5,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);
}
