import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('users').del();
  await knex('users').insert([
    {
      name: 'John Doe',
      email: 'john.doe@example.com',
      phone: '123-456-7890',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'john.doe.personal@example.com',
      gender: 'Male',
      type: 'Student',
      department_id: null,
      course_id: null,
      temporary_address: '123 Temporary St',
      permanent_address: '456 Permanent Ave',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      phone: '234-567-8901',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'jane.smith.personal@example.com',
      gender: 'Female',
      type: 'Teacher',
      department_id: null,
      course_id: null,
      temporary_address: '789 Temporary Blvd',
      permanent_address: '101 Permanent Rd',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Alice Johnson',
      email: 'alice.johnson@example.com',
      phone: '345-678-9012',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'alice.johnson.personal@example.com',
      gender: 'Female',
      type: 'Admin',
      department_id: null,
      course_id: null,
      temporary_address: '111 Temporary Lane',
      permanent_address: '222 Permanent Blvd',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Robert Brown',
      email: 'robert.brown@example.com',
      phone: '456-789-0123',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'robert.brown.personal@example.com',
      gender: 'Male',
      type: 'Manager',
      department_id: null,
      course_id: null,
      temporary_address: '333 Temporary Blvd',
      permanent_address: '444 Permanent Ave',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Emily Davis',
      email: 'emily.davis@example.com',
      phone: '567-890-1234',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'emily.davis.personal@example.com',
      gender: 'Female',
      type: 'Staff',
      department_id: null,
      course_id: null,
      temporary_address: '555 Temporary Lane',
      permanent_address: '666 Permanent Blvd',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Michael Wilson',
      email: 'michael.wilson@example.com',
      phone: '678-901-2345',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'michael.wilson.personal@example.com',
      gender: 'Male',
      type: 'Developer',
      department_id: null,
      course_id: null,
      temporary_address: '777 Temporary Blvd',
      permanent_address: '888 Permanent Ave',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Sarah Martinez',
      email: 'sarah.martinez@example.com',
      phone: '789-012-3456',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'sarah.martinez.personal@example.com',
      gender: 'Female',
      type: 'Organizer',
      department_id: null,
      course_id: null,
      temporary_address: '999 Temporary Lane',
      permanent_address: '1010 Permanent Blvd',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'David Garcia',
      email: 'david.garcia@example.com',
      phone: '890-123-4567',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'david.garcia.personal@example.com',
      gender: 'Male',
      type: 'Super Admin',
      department_id: null,
      course_id: null,
      temporary_address: '1111 Temporary Blvd',
      permanent_address: '1212 Permanent Ave',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Laura Gonzalez',
      email: 'laura.gonzalez@example.com',
      phone: '901-234-5678',
      password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a',
      is_active: true,
      personal_email: 'laura.gonzalez.personal@example.com',
      gender: 'Female',
      type: 'Staff',
      department_id: null,
      course_id: null,
      temporary_address: '1313 Temporary Blvd',
      permanent_address: '1414 Permanent Ave',
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
  ]);
}
