import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('users').del();
  await knex('users').insert([
    {
      name: 'John Doe',
      email: 'john.doe@example.com',
      department: 'Engineering',
      phone: '123-456-7890',
      password: 'hashedpassword1',
      is_active: true,
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      department: 'Marketing',
      phone: '234-567-8901',
      password: 'hashedpassword2',
      is_active: true,
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Alice Johnson',
      email: 'alice.johnson@example.com',
      department: 'Sales',
      phone: '345-678-9012',
      password: 'hashedpassword3',
      is_active: true,
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Bob Brown',
      email: 'bob.brown@example.com',
      department: 'HR',
      phone: '456-789-0123',
      password: 'hashedpassword4',
      is_active: true,
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Charlie Davis',
      email: 'charlie.davis@example.com',
      department: 'Finance',
      phone: '567-890-1234',
      password: 'hashedpassword5',
      is_active: true,
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Diana Evans',
      email: 'diana.evans@example.com',
      department: 'IT',
      phone: '678-901-2345',
      password: 'hashedpassword6',
      is_active: true,
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      name: 'Ethan Foster',
      email: 'ethan.foster@example.com',
      department: 'Customer Service',
      phone: '789-012-3456',
      password: 'hashedpassword7',
      is_active: true,
      created_at: new Date(),
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
  ]);
}
