import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('menu_items').del();

  // Insert seed entries
  await knex('menu_items').insert([
    {
      cafe_id: 1,
      category_id: 1,
      unit_id: 4,
      name: 'Espresso',
      description: 'Rich and bold espresso coffee.',
      price: 200,
      max_order: 10,
      prepared_time: 5,
      availability: true,
      discount: 0.0,
      is_special: false,
      // attached a expresso image from other source than unsplash
      image_url:
        'https://images.unsplash.com/photo-1596952954288-16862d37405b?q=80&w=3687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 1,
    },
    {
      cafe_id: 1,
      category_id: 1,
      unit_id: 4,
      name: 'Latte',
      description: 'Smooth and creamy latte with steamed milk.',
      price: 280,
      max_order: 15,
      prepared_time: 7,
      availability: true,
      discount: 0.1,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1605116188325-4379d4f5aa2c?q=80&w=3687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 1,
    },
    {
      cafe_id: 2,
      category_id: 2,
      unit_id: 8,
      name: 'Chocolate Cake',
      description: 'Decadent chocolate cake with a rich frosting.',
      price: 180,
      max_order: 5,
      prepared_time: 10,
      availability: true,
      discount: 0.2,
      is_special: true,

      // chocolate cake image from other source than unsplash'
      image_url:
        'https://images.unsplash.com/photo-1464941913535-1f37bfb72880?q=80&w=3570&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 2,
    },
    {
      cafe_id: 2,
      category_id: 3,
      unit_id: 6,
      name: 'Caesar Salad',
      description: 'Fresh Caesar salad with crispy croutons.',
      price: 150,
      max_order: 20,
      prepared_time: 8,
      availability: true,
      discount: 0.0,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1669283714145-f97867f6c238?q=80&w=2848&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 2,
    },
    {
      cafe_id: 3,
      category_id: 1,
      unit_id: 4,
      name: 'Cappuccino',
      description: 'Classic cappuccino with a rich foam layer.',
      price: 250,
      max_order: 12,
      prepared_time: 6,
      availability: true,
      discount: 0.05,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1569305917876-70cb998f2a1b?q=80&w=3024&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 3,
    },
    {
      cafe_id: 1,
      category_id: 2,
      unit_id: 1,
      name: 'momo',
      description: 'Juicy and spicy momo.',
      price: 120,
      max_order: 8,
      prepared_time: 6,
      availability: true,
      discount: 0.0,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1687068328974-13261a846e58?q=80&w=3687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 1,
    },
    {
      cafe_id: 3,
      category_id: 2,
      unit_id: 2,
      name: 'Muffin',
      description: 'Freshly baked muffin with a crumbly top.',
      price: 80,
      max_order: 8,
      prepared_time: 4,
      availability: true,
      discount: 0.0,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1604882406195-d94d4888567d?q=80&w=3648&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 3,
    },
    {
      cafe_id: 3,
      category_id: 2,
      unit_id: 2,
      name: 'Blueberry Muffin',
      description: 'Freshly baked blueberry muffin with a crumbly top.',
      price: 80,
      max_order: 8,
      prepared_time: 4,
      availability: true,
      discount: 0.0,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1722251172750-3fe7ea552a16?q=80&w=2400&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 3,
    },
    {
      cafe_id: 1,
      category_id: 2,
      unit_id: 2,
      name: 'Pancakes',
      description: 'Fluffy pancakes served with maple syrup.',
      price: 150,
      max_order: 10,
      prepared_time: 10,
      availability: true,
      discount: 0.1,
      is_special: true,
      image_url:
        'https://images.unsplash.com/photo-1497445702960-c21c96af4c68?q=80&w=3570&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 1,
    },
    {
      cafe_id: 2,
      category_id: 1,
      unit_id: 4,
      name: 'Macchiato',
      description: 'Espresso with a small amount of foamed milk.',
      price: 220,
      max_order: 10,
      prepared_time: 5,
      availability: true,
      discount: 0.05,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1519091830432-41608a52904e?q=80&w=3687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 2,
    },
    {
      cafe_id: 3,
      category_id: 3,
      unit_id: 6,
      name: 'Greek Salad',
      description: 'Fresh Greek salad with feta cheese and olives.',
      price: 170,
      max_order: 12,
      prepared_time: 8,
      availability: true,
      discount: 0.0,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1589010588553-46e8e7c21788?q=80&w=3660&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 3,
    },
    {
      cafe_id: 1,
      category_id: 2,
      unit_id: 2,
      name: 'Brownie',
      description: 'Chewy and rich chocolate brownie.',
      price: 100,
      max_order: 8,
      prepared_time: 6,
      availability: true,
      discount: 0.0,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1589218436045-ee320057f443?q=80&w=3568&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 1,
    },
    {
      cafe_id: 1,
      category_id: 2,
      unit_id: 1,
      name: 'Chowmin',
      description: 'Spicy and delicious chowmin.',
      price: 150,
      max_order: 8,
      prepared_time: 6,
      availability: true,
      discount: 0.0,
      is_special: false,
      image_url:
        'https://images.unsplash.com/photo-1601002177343-070d8f2d3496?q=80&w=3648&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      status: 'Available',
      created_by: 1,
    },
  ]);
}
