import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('reviews').del(); // Clear existing data
  await knex('reviews').insert([
    {
      user_id: 1,
      cafe_id: 1,
      menu_item_id: 1,
      rating: 5,
      comment: 'Excellent coffee and service!',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      user_id: 2,
      cafe_id: 2,
      menu_item_id: 2,
      rating: 4,
      comment: 'Great atmosphere but a bit noisy.',
      created_by: 2,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      user_id: 3,
      cafe_id: 3,
      menu_item_id: 3,
      rating: 3,
      comment: 'Average experience. Could improve.',
      created_by: 3,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      user_id: 4,
      cafe_id: 4,
      menu_item_id: 4,
      rating: 5,
      comment: 'Loved the bagels. Will visit again.',
      created_by: 4,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      user_id: 5,
      cafe_id: 5,
      menu_item_id: 5,
      rating: 4,
      comment: 'Good croissants but a bit pricey.',
      created_by: 5,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      user_id: 6,
      cafe_id: 6,
      menu_item_id: 6,
      rating: 5,
      comment: 'The muffins are delicious!',
      created_by: 6,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      user_id: 7,
      cafe_id: 7,
      menu_item_id: 7,
      rating: 4,
      comment: 'Nice brownie, but service was slow.',
      created_by: 7,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
  ]);
}
