import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('menu_units').del();

  // Insert seed entries
  await knex('menu_units').insert([
    {
      name: 'Plate',
      symbol: 'PLT',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Piece',
      symbol: 'PCS',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Glass',
      symbol: 'GLS',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Cup',
      symbol: 'CUP',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Bottle',
      symbol: 'BTL',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Bowl',
      symbol: 'BWL',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Tray',
      symbol: 'TRY',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Slice',
      symbol: 'SLC',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Bucket',
      symbol: 'BUC',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Can',
      symbol: 'CAN',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Box',
      symbol: 'BOX',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Carton',
      symbol: 'CRT',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
    {
      name: 'Bag',
      symbol: 'BAG',
      created_by: 1,
      created_at: new Date(),
      updated_by: null,
      updated_at: null,
      deleted_by: null,
      deleted_at: null,
    },
  ]);
}
